import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { ReactNode } from "react";
import Container from "./Container";
import manifest from "../pages/manifest.json";
import clsx from "clsx";

type Props = {
  children: ReactNode;
};

export default function Layout({ children }: Props) {
  const [menuOpen, setMenuOpen] = useState(false);
  const { pathname } = useRouter();

  useEffect(() => {
    if (menuOpen) {
      document.body.classList.add("overflow-hidden");
    } else {
      document.body.classList.remove("overflow-hidden");
    }
  }, [menuOpen]);

  useEffect(() => {
    setMenuOpen(false);
  }, [pathname]);

  return (
    <div ecss="antialiased line-h=relaxed">
      <Head>
        <title>emergentcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header ecss="border-(bw=1 c=neutral-900) bg-c=black sticky t=0">
        <Container>
          <div ecss="flex justify-c=between align-i=center h=16">
            <div ecss="center gap=2">
              <Link href="/">
                <a ecss="flex align-i=center gap=2">
                  <svg
                    width="30"
                    height="30"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M18.364 5.63604C19.6226 6.89471 20.4798 8.49836 20.8271 10.2442C21.1743 11.99 20.9961 13.7996 20.3149 15.4442C19.6337 17.0887 18.4802 18.4943 17.0001 19.4832C15.5201 20.4722 13.78 21 12 21C10.22 21 8.47991 20.4722 6.99987 19.4832C5.51982 18.4943 4.36627 17.0887 3.68508 15.4441C3.0039 13.7996 2.82567 11.99 3.17293 10.2442C3.5202 8.49836 4.37737 6.89471 5.63604 5.63604L12 12L18.364 5.63604Z"
                      fill="white"
                    />
                    <circle
                      cx="12"
                      cy="12"
                      r="9"
                      stroke="white"
                      strokeWidth="2"
                    />
                  </svg>
                  <span ecss="font-(s=xl w=semibold)">emergentcss</span>
                </a>
              </Link>
            </div>
            <nav ecss="center font-w=medium gap=4 text-c=neutral-200">
              <a
                target="_blank"
                rel="noreferrer"
                href="https://github.com/hanneslund/emergentcss"
              >
                <svg height="24" viewBox="2 2 20 20" fill="none">
                  <path
                    fillRule="evenodd"
                    clipRule="evenodd"
                    d="M12 3C7.0275 3 3 7.12937 3 12.2276C3 16.3109 5.57625 19.7597 9.15374 20.9824C9.60374 21.0631 9.77249 20.7863 9.77249 20.5441C9.77249 20.3249 9.76125 19.5982 9.76125 18.8254C7.5 19.2522 6.915 18.2602 6.735 17.7412C6.63375 17.4759 6.19499 16.6569 5.8125 16.4378C5.4975 16.2647 5.0475 15.838 5.80124 15.8264C6.51 15.8149 7.01625 16.4954 7.18499 16.7723C7.99499 18.1679 9.28875 17.7758 9.80625 17.5335C9.885 16.9337 10.1212 16.53 10.38 16.2993C8.3775 16.0687 6.285 15.2728 6.285 11.7432C6.285 10.7397 6.63375 9.9092 7.20749 9.26326C7.1175 9.03257 6.8025 8.08674 7.2975 6.81794C7.2975 6.81794 8.05125 6.57571 9.77249 7.76377C10.4925 7.55615 11.2575 7.45234 12.0225 7.45234C12.7875 7.45234 13.5525 7.55615 14.2725 7.76377C15.9937 6.56418 16.7475 6.81794 16.7475 6.81794C17.2424 8.08674 16.9275 9.03257 16.8375 9.26326C17.4113 9.9092 17.76 10.7281 17.76 11.7432C17.76 15.2843 15.6563 16.0687 13.6537 16.2993C13.98 16.5877 14.2613 17.1414 14.2613 18.0065C14.2613 19.2407 14.25 20.2326 14.25 20.5441C14.25 20.7863 14.4188 21.0746 14.8688 20.9824C16.6554 20.364 18.2079 19.1866 19.3078 17.6162C20.4077 16.0457 20.9995 14.1611 21 12.2276C21 7.12937 16.9725 3 12 3Z"
                    fill="currentColor"
                  ></path>
                </svg>
              </a>
              <button onClick={() => setMenuOpen(!menuOpen)} ecss="@md:hidden">
                {menuOpen ? (
                  <svg
                    viewBox="0 0 24 24"
                    width="24"
                    height="24"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <line x1="18" y1="6" x2="6" y2="18"></line>
                    <line x1="6" y1="6" x2="18" y2="18"></line>
                  </svg>
                ) : (
                  <svg
                    viewBox="0 0 24 24"
                    width="24"
                    height="24"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    fill="none"
                    shapeRendering="geometricPrecision"
                  >
                    <path d="M3 12h18"></path>
                    <path d="M3 6h18"></path>
                    <path d="M3 18h18"></path>
                  </svg>
                )}
              </button>
            </nav>
          </div>
        </Container>
      </header>
      <Container>
        <div ecss="p-y=12">
          <aside
            className={clsx(
              "bg-black fixed inset-0 top-16 md:inset-auto p-6 md:p-0 overflow-y-auto md:w-52 md:pb-32 md:h-[calc(100vh-7rem)] md:block",
              { hidden: !menuOpen }
            )}
          >
            {manifest.sections.map((section) => (
              <React.Fragment key={section.title}>
                <h5 ecss="font-w=semibold m-t=10 first:m-t=0">
                  {section.title}
                </h5>
                <div ecss="font-s=sm flex flex-d=col m-(l=2 t=4) p-(l=4 y=2) border-(lw=1 c=neutral-800) gap=4 text-c=neutral-400">
                  {section.routes.map((route) => (
                    <Link key={route.route} href={`/${route.route}`}>
                      <a
                        className={clsx("hover:text-neutral-50", {
                          "font-bold text-neutral-50":
                            pathname === `/${route.route}`,
                        })}
                      >
                        {route.title}
                      </a>
                    </Link>
                  ))}
                </div>
              </React.Fragment>
            ))}
          </aside>
          <main ecss="@md:p-l=72">{children}</main>
        </div>
      </Container>
    </div>
  );
}
